#!/usr/bin/env bash
#
# Promote the current working tree to ficatlas.com with no downtime.
#
#     deploy/promote.sh              # build, verify, switch
#     deploy/promote.sh --dry-run    # say what it would do
#     deploy/promote.sh --rollback   # switch back to the other colour
#     deploy/promote.sh --status     # what is live now
#
# The shape of it: the public site is served through nginx, which points at ONE
# of two colours. This starts the colour that is NOT live, waits for it to
# actually answer, and only then repoints nginx and reloads. A reload finishes
# in-flight requests on the old workers, so nobody sees a connection drop and
# nobody sees a half-started app — the new colour has already proven it serves
# before a single visitor reaches it.
#
# Rollback is the same switch in reverse, and it is instant BECAUSE the old
# colour is only stopped after a grace period. That window is the entire reason
# the previous version is still sitting there.
#
# What this deliberately does NOT do
# ----------------------------------
# It does not run migrations. The database is shared with the dev stack, DDL is
# applied by init_db.py at API start-up, and it is idempotent and additive. A
# deploy that needed a destructive migration would need the two colours to
# tolerate both schemas at once, and that is a decision to make deliberately in
# the moment, not something a script should do quietly at 2am.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
ROOT=$(pwd)

PROJECT=ficatlas-public
COMPOSE=(docker compose -p "$PROJECT" -f docker-compose.public.yml)
ACTIVE_CONF="$ROOT/deploy/upstreams/active.conf"
# How long the old colour stays up after the switch, so a rollback is a reload
# rather than a rebuild.
GRACE_SECONDS=${GRACE_SECONDS:-120}
HEALTH_TIMEOUT=${HEALTH_TIMEOUT:-180}

c_ok()   { printf '\033[32m%s\033[0m\n' "$*"; }
c_warn() { printf '\033[33m%s\033[0m\n' "$*"; }
c_err()  { printf '\033[31m%s\033[0m\n' "$*" >&2; }
step()   { printf '\n\033[1m==> %s\033[0m\n' "$*"; }

live_colour() {
    # The single source of truth for what is live is what nginx is pointed at,
    # not a file we keep alongside it that could disagree.
    grep -oE 'server web-(blue|green):' "$ACTIVE_CONF" | grep -oE 'blue|green' | head -1
}

other_colour() { [ "$1" = blue ] && echo green || echo blue; }

require_env() {
    local missing=()
    for v in CLOUDFLARE_TUNNEL_TOKEN POSTGRES_PASSWORD; do
        # shellcheck disable=SC2015
        grep -qE "^${v}=.+" "$ROOT/.env" 2>/dev/null || missing+=("$v")
    done
    if [ ${#missing[@]} -gt 0 ]; then
        c_err "Missing in .env: ${missing[*]}"
        exit 1
    fi
}

write_upstreams() {
    local colour=$1
    cat > "$ACTIVE_CONF" <<EOF
# WHICH COLOUR IS LIVE. Generated by deploy/promote.sh — do not edit by hand.
# Switched to ${colour} at $(date -Is).
#
# max_fails=0 is deliberate: with one server in the pool, nginx's default
# ejection would 502 every request for 10s after a single slow response.
# Health is decided by promote.sh before the switch, not by nginx after it.

upstream web_active {
    server web-${colour}:3000 max_fails=0;
    keepalive 32;
}

upstream api_active {
    server api-${colour}:8000 max_fails=0;
    keepalive 32;
}
EOF
}

wait_healthy() {
    local svc=$1 deadline=$((SECONDS + HEALTH_TIMEOUT))
    printf '    waiting for %s ' "$svc"
    while [ $SECONDS -lt $deadline ]; do
        local cid status
        cid=$("${COMPOSE[@]}" ps -q "$svc" 2>/dev/null | head -1)
        if [ -n "$cid" ]; then
            status=$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$cid" 2>/dev/null || echo none)
            case "$status" in
                healthy) echo; c_ok "    $svc is healthy"; return 0 ;;
                unhealthy) echo; c_err "    $svc reported UNHEALTHY"; return 1 ;;
            esac
        fi
        printf '.'; sleep 3
    done
    echo; c_err "    $svc did not become healthy within ${HEALTH_TIMEOUT}s"
    return 1
}

reload_nginx() {
    # -s reload, not a restart: nginx starts new workers with the new upstream
    # and lets the old ones drain. A restart would drop every open connection,
    # which is the thing this whole arrangement exists to avoid.
    "${COMPOSE[@]}" exec -T nginx nginx -s reload
}

verify_through_nginx() {
    # Through nginx, exactly as a visitor arrives — not against the container
    # directly. This is what catches a switch that pointed at the wrong place.
    "${COMPOSE[@]}" exec -T nginx wget -q -O- --timeout=25 http://127.0.0.1:8080/ >/dev/null
}

cmd_status() {
    local live
    live=$(live_colour || echo "unknown")
    echo "live colour : ${live}"
    echo "project     : ${PROJECT}"
    "${COMPOSE[@]}" ps --format '  {{.Service}}\t{{.Status}}' 2>/dev/null || true
    echo
    echo "public DNS  : $(dig +short ficatlas.com A 2>/dev/null | head -1 || echo '(not resolving)')"
}

cmd_rollback() {
    local live target
    live=$(live_colour)
    target=$(other_colour "$live")
    step "Rolling back: ${live} -> ${target}"
    if ! "${COMPOSE[@]}" ps --status running --format '{{.Service}}' | grep -qx "web-${target}"; then
        c_err "web-${target} is not running — nothing to roll back to."
        c_err "The previous colour is only kept for ${GRACE_SECONDS}s after a promote."
        exit 1
    fi
    write_upstreams "$target"
    reload_nginx
    verify_through_nginx && c_ok "Rolled back to ${target}."
}

cmd_promote() {
    local dry=$1
    require_env

    local live target tag
    live=$(live_colour)
    target=$(other_colour "$live")
    tag=$(git rev-parse --short HEAD)
    # A dirty tree would produce an image that matches no commit, and the whole
    # point of tagging by SHA is being able to say what is running.
    #
    # active.conf is excluded because THIS SCRIPT rewrites it on every deploy, so
    # counting it would mark every deploy after the first as dirty and the tag
    # would stop meaning anything. It stays tracked rather than ignored so a
    # fresh clone has a valid upstream file and nginx can start at all.
    if [ -n "$(git status --porcelain -- . ':(exclude)deploy/upstreams/active.conf')" ]; then
        tag="${tag}-dirty"
        c_warn "Working tree is dirty — tagging ${tag}"
    fi

    echo "live now      : ${live}"
    echo "deploying to  : ${target}"
    echo "image tag     : ${tag}"
    if [ "$dry" = yes ]; then
        echo
        c_warn "--dry-run: stopping here."
        return 0
    fi

    step "Building images (the live site keeps serving throughout)"
    DEPLOY_TAG=$tag docker build -q -t "ficatlas-frontend:${tag}" ./frontend
    DEPLOY_TAG=$tag docker build -q -t "ficatlas-backend:${tag}"  ./backend
    c_ok "built ficatlas-frontend:${tag} and ficatlas-backend:${tag}"

    step "Starting the ${target} colour"
    COMPOSE_PROFILES=$target DEPLOY_TAG=$tag "${COMPOSE[@]}" --profile "$target" up -d \
        "api-${target}" "web-${target}"

    step "Verifying it actually serves"
    wait_healthy "api-${target}" || { c_err "Aborting; ${live} is untouched and still live."; exit 1; }
    wait_healthy "web-${target}" || { c_err "Aborting; ${live} is untouched and still live."; exit 1; }

    step "Switching nginx ${live} -> ${target}"
    write_upstreams "$target"
    reload_nginx

    if ! verify_through_nginx; then
        c_err "Post-switch check failed — reverting to ${live}."
        write_upstreams "$live"
        reload_nginx
        exit 1
    fi
    c_ok "ficatlas.com is now served by ${target} (${tag})"

    step "Keeping ${live} for ${GRACE_SECONDS}s so rollback is instant"
    echo "    deploy/promote.sh --rollback   # if anything looks wrong"
    sleep "$GRACE_SECONDS"
    COMPOSE_PROFILES=$live "${COMPOSE[@]}" --profile "$live" stop "api-${live}" "web-${live}" >/dev/null 2>&1 || true
    c_ok "Stopped ${live}. Deploy complete."

    step "Reclaiming disk"
    # Not optional housekeeping on this box. The backend image is ~12GB, the
    # database volume is ~41GB, and the disk runs at 80%. One build left 26GB of
    # build cache behind; a few tagged deploys without this would fill the disk,
    # and a full disk stops Postgres writing — the site would fail for a reason
    # with nothing to do with the deploy that caused it.
    docker builder prune -af >/dev/null 2>&1 || true
    # Keep the last few tags so --rollback has something to roll back TO, and so
    # a bad deploy can be pinned back to a known-good SHA by hand.
    for repo in ficatlas-frontend ficatlas-backend; do
        docker images --format '{{.Tag}} {{.ID}} {{.CreatedAt}}' "$repo" \
            | grep -vE '^(latest|<none>) ' | sort -k3 -r | tail -n +4 \
            | while read -r t _ _; do
                  [ -n "$t" ] && docker rmi "${repo}:${t}" >/dev/null 2>&1 || true
              done
    done
    docker image prune -f >/dev/null 2>&1 || true
    df -h / | tail -1 | awk '{print "    disk: "$4" free ("$5" used)"}'
}

case "${1:-}" in
    --status)   cmd_status ;;
    --rollback) cmd_rollback ;;
    --dry-run)  cmd_promote yes ;;
    "")         cmd_promote no ;;
    *) echo "usage: $0 [--dry-run|--rollback|--status]" >&2; exit 2 ;;
esac
